### ISSUE TITLE
error while loading shared libraries

### ISSUE THREAD

**Issue by mohamed-barakat** [JuliaBinaryWrappers/lib4ti2_jll.jl#1]
In the attempt to investigate the test failure here

https://travis-ci.com/github/homalg-project/HomalgProject.jl/jobs/336415996

I ran the test in an ubuntu docker container and isolated the following problem:

```
# /root/.julia/artifacts/12659962696a028b1c8657f6de30ff2f9e2b2c16/bin/hilbert
/root/.julia/artifacts/12659962696a028b1c8657f6de30ff2f9e2b2c16/bin/zsolve: error while loading shared libraries: libgmpxx.so.4: cannot open shared object file: No such file or directory
```

**Comment by mohamed-barakat** [comment]
@fingolfin

**Comment by mohamed-barakat** [comment]
The issue is resolved after

```
apt-get install libgmp-dev
```

**Comment by mohamed-barakat** [comment]
```bash
# /root/.julia/artifacts/12659962696a028b1c8657f6de30ff2f9e2b2c16/bin/groebner
/root/.julia/artifacts/12659962696a028b1c8657f6de30ff2f9e2b2c16/bin/4ti2gmp: error while loading shared libraries: libglpk.so.40: cannot open shared object file: No such file or directory
```

**Comment by mohamed-barakat** [comment]
The missing `libglpk.so.40` issue was resolved after
```bash
apt-get install libglpk
```

**Comment by fingolfin** [comment]
Those are *not* correct solutions! If you do that, you might as well install 4ti2 via apt-get and don't bother with this JLL.

You don't actually say which code you run. But it seems you are calling the `hilbert` script directly. That won't work. Please re-read my original mail to @fieker and you, it describes how to do it.

**Comment by fieker** [comment]
On Mon, May 18, 2020 at 11:57:20PM -0700, Max Horn wrote:
> Those are *not* correct solutions! If you do that, you might as well install 4ti2 via apt-get and don't bother with this JLL.
> 
> You don't actually say which code you run. But it seems you are calling the `hilbert` script directly. That won't work. Please re-read my original mail to @fieker and you, it describes how to do it.
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/JuliaBinaryWrappers/lib4ti2_jll.jl/issues/1#issuecomment-630623551

The problem with Markov is actually in two parts
 - the markov() function (similar to zsolve) is missing
 - the referenced shared library is simply not there...
Where is the original builder for this? It appears that a
"LibraryProduct" (or more) is missing - or that we need a second jll for
the libglpk as a dependency for this.
Given that markov was build, the library was present at this time.

**Comment by fieker** [comment]
Update: GLPK_jll esists and is there.
the markov function is missing, I guess it currently is a "FileProduct" and needs to be an "ExecutableProduct"

**Comment by fieker** [comment]
Patching the generated loader by hand so that markov does exactly the same as zsolve solves this problem

**Comment by mohamed-barakat** [comment]
The following shell scripts suggested by @fingolfin in a previous email are the correct solution:

```
#!/bin/sh
# graver
julia -e 'import lib4ti2_jll
lib4ti2_jll.zsolve() do x
 p=run(ignorestatus(`$x -G $ARGS`))
 exit(p.exitcode)
end' -- "$@"

#!/bin/sh
# hilbert
julia -e 'import lib4ti2_jll
lib4ti2_jll.zsolve() do x
 p=run(ignorestatus(`$x -H $ARGS`))
 exit(p.exitcode)
end' -- "$@"

#!/bin/sh
# markov
julia -e 'import lib4ti2_jll
lib4ti2_jll.exe4ti2gmp() do x
 p=run(ignorestatus(`$x markov $ARGS`))
 exit(p.exitcode)
end' -- "$@"
```
